export default {
  navigationBarTitleText: '服务器管理',
  usingComponents: {
    'van-notify': '../../components/vant-weapp/dist/notify/index',
    'van-circle': '../../components/vant-weapp/dist/circle/index',
    'van-popup': '../../components/vant-weapp/dist/popup/index',
    'van-sidebar': '../../components/vant-weapp/dist/sidebar/index',
    'van-sidebar-item': '../../components/vant-weapp/dist/sidebar-item/index',
    'van-swipe-cell': '../../components/vant-weapp/dist/swipe-cell/index',
    'van-collapse': '../../components/vant-weapp/dist/collapse/index',
    'van-collapse-item': '../../components/vant-weapp/dist/collapse-item/index',
    'van-search': '../../components/vant-weapp/dist/search/index',
    'van-progress': '../../components/vant-weapp/dist/progress/index',
    'van-loading': '../../components/vant-weapp/dist/loading/index',
    'van-icon': '../../components/vant-weapp/dist/icon/index',
    'van-tag': '../../components/vant-weapp/dist/tag/index',
    'van-cell-group': '../../components/vant-weapp/dist/cell-group/index',
    'van-sticky': '../../components/vant-weapp/dist/sticky/index',
  },
  enablePullDownRefresh: true,
  backgroundTextStyle: 'dark',
};
