export default {
  navigationBarTitleText: '自定义配置',
  usingComponents: {
    'van-panel': '../../components/vant-weapp/dist/panel/index',
    'van-cell': '../../components/vant-weapp/dist/cell/index',
    'van-cell-group': '../../components/vant-weapp/dist/cell-group/index',
    'van-icon': '../../components/vant-weapp/dist/icon/index',
    'van-field': '../../components/vant-weapp/dist/field/index',
    'van-card': '../../components/vant-weapp/dist/card/index',
    'van-button': '../../components/vant-weapp/dist/button/index',
    'van-notify': '../../components/vant-weapp/dist/notify/index',
    'van-toast': '../../components/vant-weapp/dist/toast/index',
    'van-tag': '../../components/vant-weapp/dist/tag/index',
    'van-image': '../../components/vant-weapp/dist/image/index',
    'van-grid': '../../components/vant-weapp/dist/grid/index',
    'van-grid-item': '../../components/vant-weapp/dist/grid-item/index',
    'van-circle': '../../components/vant-weapp/dist/circle/index',
    'van-popup': '../../components/vant-weapp/dist/popup/index',
    'van-sidebar': '../../components/vant-weapp/dist/sidebar/index',
    'van-sidebar-item': '../../components/vant-weapp/dist/sidebar-item/index',
    'van-collapse': '../../components/vant-weapp/dist/collapse/index',
    'van-collapse-item': '../../components/vant-weapp/dist/collapse-item/index',
    'van-row': '../../components/vant-weapp/dist/row/index',
    'van-col': '../../components/vant-weapp/dist/col/index',
    'van-search': '../../components/vant-weapp/dist/search/index',
    'van-switch': '../../components/vant-weapp/dist/switch/index',
    'van-stepper': '../../components/vant-weapp/dist/stepper/index',
    'van-dropdown-menu': '../../components/vant-weapp/dist/dropdown-menu/index',
    'van-dropdown-item': '../../components/vant-weapp/dist/dropdown-item/index',
  },
};
